### ISSUE TITLE
颜色渲染

### ISSUE THREAD

**Issue by cici0007** [chenwenhang/MathFunctionTool#1]
能增加功能：把闭合曲线以某种颜色渲染出来吗，栓Q外瑞玛驰~~~

**Comment by chenwenhang** [comment]
你好，感谢反馈：
1.  关于闭合曲线，本身就支持，用隐函数或参数方程都可以实现，例如隐函数实现：0 = x^2+y^2-1。
2. 已添加【设置函数颜色功能】，支持16进制、RGB和颜色的英文名称。
